name: CI Pull Request Into Main
on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.100
        
    - name: Checkout code
      uses: actions/checkout@v2
       
    - name: Restore dependencies
      run: dotnet restore ./src/DavesDartsClub.sln
      
    - name: Build
      run: dotnet build ./src/DavesDartsClub.sln --no-restore
      
    - name: Test
      run: dotnet test ./src/DavesDartsClub.sln --no-build --verbosity normal
